myproyect/myproyect/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

myproyect/task/urls.py
from django.urls import path

from . import views

app_name = "task"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:task_id>/", views.detail, name="detail"),
]

myproyect/task/models.py
from django.db import models
import datetime
from time import timezone


class Task(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    fecha_limite = models.DateTimeField("fecha limite")
    estado = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

    def was_published_recently(self):
        return self.fecha_limite >= timezone.now() - datetime.timedelta(days=1)

myproyect/task/views.py
from django.shortcuts import get_object_or_404, render
from .models import Task


def index(request):
    latest_task_list = Task.objects.order_by("-fecha_realizar")[:5]
    context = {"latest_task_list": latest_task_list}
    return render(request, "task/index.html", context)


def detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    return render(request, "task/detail.html", {"task": task})

myproyect/task/templates/task/detail.html
<h1>{{ task.nombre }}</h1>
<ul>
{% for task in task.task.all %}
    <li>{{ task.nombre }}</li>
{% endfor %}
</ul>

myproyect/task/templates/task/index.html
{% if latest_task_list %}
    <ul>
    {% for task in latest_task_list %}
    <li><a href="{% url 'task:detail' task.id %}">{{ task.nombre }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}